//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicTac
{
	
	
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int tack = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int tick = 2130837506;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060001
			public const int ImgButton00 = 2131099649;
			
			// aapt resource value: 0x7f060004
			public const int ImgButton01 = 2131099652;
			
			// aapt resource value: 0x7f060007
			public const int ImgButton02 = 2131099655;
			
			// aapt resource value: 0x7f060002
			public const int ImgButton10 = 2131099650;
			
			// aapt resource value: 0x7f060005
			public const int ImgButton11 = 2131099653;
			
			// aapt resource value: 0x7f060008
			public const int ImgButton12 = 2131099656;
			
			// aapt resource value: 0x7f060003
			public const int ImgButton20 = 2131099651;
			
			// aapt resource value: 0x7f060006
			public const int ImgButton21 = 2131099654;
			
			// aapt resource value: 0x7f060009
			public const int ImgButton22 = 2131099657;
			
			// aapt resource value: 0x7f060000
			public const int linearLayout3 = 2131099648;
			
			// aapt resource value: 0x7f06000b
			public const int menu_close = 2131099659;
			
			// aapt resource value: 0x7f06000a
			public const int menu_new = 2131099658;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f050000
			public const int OptionalMenu = 2131034112;
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			private String()
			{
			}
		}
	}
}
